version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-ci
    ports:
      - "3000:3000"
    networks:
      - red-ci

  frontend:
    build: ./frontend
    container_name: frontend-ci
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - red-ci

networks:
  red-ci:
    driver: bridge